version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  celery:
    build:
      context: .
    command: celery -A loan  worker --loglevel=info
    depends_on:
      - rabbitmq
    restart: always
  loan:
    image: loan
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - celery
  
  
