# Generated by Django 4.2.2 on 2023-06-20 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255, unique=True)),
                ('field_type', models.CharField(choices=[('char_field', 'char_field'), ('integer_field', 'integer_field'), ('boolean_field', 'boolean_field'), ('date_field', 'date_field'), ('decimal_field', 'decimal_field')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanProposalField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255, unique=True)),
                ('field_type', models.CharField(choices=[('char_field', 'char_field'), ('integer_field', 'integer_field'), ('boolean_field', 'boolean_field'), ('date_field', 'date_field'), ('decimal_field', 'decimal_field')], max_length=100)),
                ('data', models.CharField(max_length=255)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_loan.loanproposal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
