# Generated by Django 4.2.2 on 2023-06-20 20:13

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characteres are allowed'), django.core.validators.MinLengthValidator(11)])),
                ('address', models.CharField(max_length=255)),
                ('loan_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('refused', 'refused')], max_length=10)),
            ],
        ),
    ]
